### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by Simplenuity** [caarlos0/msfonts#1]
Hi,
I came across these fonts while searching for a wingdings font version I can install on Linux to get ToDoList running via Wine to display a few icons correctly (see: https://github.com/abstractspoon/ToDoList_Issues/issues/64).
What is the license situation around these msfonts on here? Are they free to download and being mentioned as free resource for ToDoList?
Thanks in advance!

**Comment by caarlos0** [comment]
probably not, they are MS fonts after all...

**Comment by Simplenuity** [comment]
Thanks for the quick reply.

**Comment by caarlos0** [comment]
@Simplenuity no problem ;)
